version: '3.9'
services:
  restservice:
    container_name: okx-bot-rest-service
    image: okx-bot-rest-service:1.0.1
    build:
      dockerfile: rest.Dockerfile
    ports:
      - '8000:8000'
    environment:
      - db_user=vpomo
      - db_pass=admin
      - db_name=okx-bot
      - db_host=db
    depends_on:
      - db
    networks:
      - postgres
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: vpomo
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: okx-bot
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - '5432:5432'
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  pgdata: {}
